<?xml version="1.0" encoding="utf-8"?><Database Name="MMABooks" Class="MembershipDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost\sqlexpress;Initial Catalog=MMABooks;Integrated Security=True" SettingsObjectName="LINDClass.Properties.Settings" SettingsPropertyName="MMABooksConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Membership" Member="Memberships">
    <Type Name="Membership">
      <Column Name="MemberID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MemberName" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="DateStarted" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateEnded" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>